import { writeFile } from "node:fs/promises";
import path from "node:path";
import { assertFfmpeg, probeJson, run } from "./lib/ffmpeg.mjs";
import { ensureDirectory, fileExists, fromRoot } from "./lib/filesystem.mjs";
import {
  MASTER_DURATION,
  SAMPLE_FPS,
  SOURCE_FILES,
} from "./lib/manifest.mjs";

const sourceDirectory = fromRoot("source-assets", "video");
const outputDirectory = fromRoot("output", "video-inspection");
const reportFile = fromRoot("docs", "video-processing-report.md");
const { ffmpeg, ffprobe } = assertFfmpeg();

await ensureDirectory(outputDirectory);
await ensureDirectory(path.dirname(reportFile));

const missing = [];
const metadata = [];
for (const name of SOURCE_FILES) {
  const source = path.join(sourceDirectory, name);
  if (!(await fileExists(source))) {
    missing.push(source);
    continue;
  }
  const probe = await probeJson(ffprobe, source, "format=filename,duration,size:stream=codec_name,width,height,avg_frame_rate,pix_fmt,nb_frames");
  metadata.push({ name, ...probe });
  await writeFile(path.join(outputDirectory, `${path.parse(name).name}.json`), `${JSON.stringify(probe, null, 2)}\n`);
  await run(ffmpeg, [
    "-hide_banner", "-loglevel", "error", "-y", "-i", source,
    "-vf", "fps=1,scale=480:-2,tile=4x2", "-frames:v", "1",
    path.join(outputDirectory, `${path.parse(name).name}-contact.jpg`),
  ]);
}

if (missing.length) throw new Error(`Missing source videos:\n${missing.join("\n")}`);

const rows = metadata.map(({ name, streams, format }) => {
  const video = streams.find((stream) => stream.width);
  return `| ${name} | ${Number(format.duration).toFixed(3)} s | ${video.width}×${video.height} | ${video.avg_frame_rate} | ${video.codec_name} | ${video.pix_fmt} |`;
}).join("\n");
const expectedFrames = Math.round(MASTER_DURATION * SAMPLE_FPS);

const report = `# Video processing report

Generated by \`npm run video:inspect\`.

## Source inventory

| Source | Duration | Dimensions | Frame rate | Codec | Pixel format |
| --- | ---: | ---: | ---: | --- | --- |
${rows}

All four videos are 1920×1080, 24 fps H.264 with yuv420p video. Source audio is discarded during normalization.

## Editorial inspection

Contact sheets are written to \`output/video-inspection/\` and intentionally gitignored.

- Transition 01: coherent mountain-to-station approach; retain full 8.000 seconds.
- Transition 02: retain the full 8.000-second move. Its final 2.700 seconds carry the camera through the threshold and land on the composition that opens transition 03; trimming them creates a visible jump.
- Transition 03: coherent entrance-to-corridor move with a stable corridor landing; retain full 8.000 seconds.
- Transition 04: coherent corridor-to-control-room move; retain the final stable waveform display at 8.000 seconds.

## Processing decisions

- Normalize each usable segment to 1920×1080, 24 fps, H.264, yuv420p, CFR, without audio.
- Concatenate all four complete normalized transitions in source order without overlap or crossfade.
- Sample the ${MASTER_DURATION.toFixed(3)}-second master at ${SAMPLE_FPS} fps. This produces ${expectedFrames} frames, within the requested 320–420 useful-frame envelope while preserving every source segment.
- Replace boundary sample 209 with its immediate forward neighbor at the 02→03 cut. Remove samples 313–314 and compact the remaining sequence to 414 frames, eliminating the reverse-and-hold artifact at the 03→04 cut.
- Generate desktop WebP at 1920×1080 (quality 38) and mobile WebP at 1080×1350 (quality 18). The mobile crop is centered through transition 03 and shifts left for transition 04 to preserve the circular display.

Exact output counts, scene indices, and sizes are written by \`npm run sequence:build\` to \`docs/sequence-manifest.md\`.
`;

await writeFile(reportFile, report);
console.log(`Inspected ${metadata.length} videos. Report: ${reportFile}`);
